import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [pokemonList, setPokemonList] = useState([])

  useEffect(() => {
    const fetchPokemonList = async () => {
      const response = await fetch('api/pokemon')
      const results = await response.json()
      setPokemonList(results)
    }
    fetchPokemonList()
  }, [])

  return (
    <>
      <Head>
        <title>Clase 6: API Routes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1>Clase 6: API Routes / Pokemon</h1>
          <nav>
            <ul>
              <li>
                <Link href={'/pokemon'}>
                  ver pokemons
                </Link>
              </li>
              <li>
                <Link href={'/pokemonx'}>
                  ver 404
                </Link>
              </li>
              <li>
                <Link href={'/pokemon500'}>
                  ver 500
                </Link>
              </li>
            </ul>
          </nav>
          <div>
            <ul>
              {pokemonList.map((pokemon: any) => {
                return (
                  <li key={pokemon.id}>
                    <Link href={`/pokemon/${pokemon.id}`}>
                      {pokemon.name}
                    </Link>
                  </li>
                )
              }
              )}
            </ul>
          </div>
        </div>
      </main>
    </>
  )
}
