import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const envVar = process.env.URL_BASE
  return (
    <>
      <Head>
        <title>Clase 6: API Routes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1>Clase 6: API Routes - Env var: {envVar}</h1>
          <nav>
            <ul>
              <li>
                <Link href={'/pokemon'}>
                  ver pokemons
                </Link>
              </li>
              <li>
                <Link href={'/pokemonx'}>
                  ver 404
                </Link>
              </li>
              <li>
                <Link href={'/pokemon500'}>
                  ver 500
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </main>
    </>
  )
}
